### ISSUE TITLE
Best quality possible?

### ISSUE THREAD

**Issue by TravelTrader** [maaaaz/webscreenshot#40]
First I have to say that it's a great tool. I am so happy that I found it!

Now I need it for a screenshot where I use the cv2 library on it. And the quality leads to about 10% errors.
[Here you can find a part of it](https://pasteboard.co/IOIhlK6.png).

My settings are
```
quality=100
window_size=2400,1000
format=jpg
...
```

Of course, I tried around with the numbers. But with highest quality the window size does not change a lot.

Any ideas or hints?
Thanks!

**Comment by maaaaz** [comment]
Hello @TravelTrader,
Thanks for your kind feedback.

I'm no expert at all in image processing, but: 
* this bad image quality (hence error-prone processing) is totally due to the capture phase ? The source image leads to 0% error ? 
* aside the `quality` and `window_size`, have you tried a different `format` ? Remember that these paremeters are only available using the `phantomjs` renderer
* can you try to use another renderer (chrome or chromium or firefox) ?

**Comment by TravelTrader** [comment]
Thanks @maaaaz. Good ideas.
I tried around but could not improve it.

For me it's a miracle why a screenshot on my desktop is much better than a screenshot using your library and a better solution... maybe it's because the code runs on a server without a window manager?

**Comment by maaaaz** [comment]
> Thanks @maaaaz. Good ideas.
> I tried around but could not improve it.

Argh! Sad to hear. 

> For me it's a miracle why a screenshot on my desktop is much better than a screenshot using your library and a better solution... maybe it's because the code runs on a server without a window manager?

I really don't know.
One other idea is that you can try to add [here](https://github.com/maaaaz/webscreenshot/blob/master/webscreenshot.js#L41) a `phantomjs` `zoomfactor` [statement](https://phantomjs.org/api/webpage/property/zoom-factor.html) like for instance `page.zoomFactor = 1.25;` (125% zoom)
