### ISSUE TITLE
Replace phantomjs by headless Google Chrome

### ISSUE THREAD

**Issue by themaks** [maaaaz/webscreenshot#7]
Hi !

phamtomjs' only maintainer [has given up](https://groups.google.com/forum/m/#!topic/phantomjs/9aI5d-LDuNE) on maintaining his software, due to the release of Google Chrome headless browser in version 59

Have you considered to migrate webscreenshot's backend accordingly ?

Thanks in advance !

😛

**Comment by maaaaz** [comment]
Hello @themaks,

Indeed Chrome headless looks promising but I haven't considered migrating right now because:
* It seems that it is [difficult to make full page screenshots](https://developers.google.com/web/updates/2017/04/headless-chrome)
* The headless mode and `--screenshot` feature are still recent and it seems that there are some bugs with transparency and background color on websites
* There is still no Windows support of Chrome headless: to date webscreenshot+phantomjs can be used on Windows
* I don't know how the **lazy-rendering**, a key feature currently implemented in webscreenshot, could be achieved with Chrome headless 

But for sure I'll migrate when things get better.

Cheers.

**Comment by maaaaz** [comment]
Hello @themaks,

It is now implemented, with the limitations mentioned in the README.

Cheers.

**Comment by themaks** [comment]
Nice, thanks !
I look forward to test it !
;)
